//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinnerSurvey.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_WGE_SURVEY2
    {
        public int ID { get; set; }
        public string NumberID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Age { get; set; }
        public string Salary { get; set; }
        public string Year { get; set; }
        public string Rate_1 { get; set; }
        public string Rate_2 { get; set; }
        public string Rate_3 { get; set; }
        public string Rate_4 { get; set; }
        public string Rate_5 { get; set; }
        public string Rate_6 { get; set; }
        public string Rate_7 { get; set; }
        public string Rate_8 { get; set; }
        public string Rate_9 { get; set; }
        public string Rate_10 { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
    }
}
