//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinnerSurvey.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_WGE_SURVEY_DETAIL
    {
        public int ID { get; set; }
        public string NumberID { get; set; }
        public string Detail { get; set; }
    }
}
