//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinnerSurvey.Models.L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_WGE_SURVEY1
    {
        public int ID { get; set; }
        public string NumberID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Code { get; set; }
        public string Cardcode { get; set; }
        public string Cardname { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Year { get; set; }
        public string RateProduct_1 { get; set; }
        public string RateProduct_2 { get; set; }
        public string RateProduct_3 { get; set; }
        public string RateProduct_4 { get; set; }
        public string RateProduct_5 { get; set; }
        public string RateProduct_6 { get; set; }
        public string RateProduct_7 { get; set; }
        public string RateTransport_1 { get; set; }
        public string RateTransport_2 { get; set; }
        public string RateTransport_3 { get; set; }
        public string RateTransport_4 { get; set; }
        public string RateService_1 { get; set; }
        public string RateService_2 { get; set; }
        public string RateService_3 { get; set; }
        public string RateService_4 { get; set; }
        public string RateCom_1 { get; set; }
        public string RateCom_2 { get; set; }
        public string RateCom_3 { get; set; }
        public string RemarkProduct { get; set; }
        public string RemarkTransport { get; set; }
        public string RemarkService { get; set; }
        public string RemarkCom { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string Generate_Report { get; set; }
        public string SlpName { get; set; }
    }
}
