//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinnerSurvey.Models.L1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBSEntities : DbContext
    {
        public DBSEntities()
            : base("name=DBSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OHEM> OHEM { get; set; }
        public virtual DbSet<C_WGE_SURVEY_DETAIL> C_WGE_SURVEY_DETAIL { get; set; }
        public virtual DbSet<CRD1> CRD1 { get; set; }
        public virtual DbSet<OACD> OACD { get; set; }
        public virtual DbSet<OCRD> OCRD { get; set; }
        public virtual DbSet<OSLP> OSLP { get; set; }
        public virtual DbSet<C_WGE_SURVEY_EMAIL> C_WGE_SURVEY_EMAIL { get; set; }
        public virtual DbSet<C_WGE_SURVEY1> C_WGE_SURVEY1 { get; set; }
        public virtual DbSet<C_WGE_SURVEY2> C_WGE_SURVEY2 { get; set; }
        public virtual DbSet<C_WGE_SURVEY_REPORT> C_WGE_SURVEY_REPORT { get; set; }
    }
}
